import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export interface ForgeFile {
  path: string;
  content: string;
}

/**
 * In-browser ZIP packaging utility for Synapse Forge projects.
 * Bundles all generated code files, injects cross-platform run scripts (run.bat and run.sh),
 * ensures a setup README.md is present, and triggers an uncorrupted .zip download.
 */
export async function exportForgeProject(
  projectName: string,
  files: Array<ForgeFile>,
  runScript: string
): Promise<void> {
  const zip = new JSZip();
  const safeProjectName = (projectName || 'synapse-forge-app')
    .toLowerCase()
    .replace(/[^a-z0-9-_]/g, '-');

  // 1. Write each generated file to its relative path
  files.forEach((file) => {
    const cleanPath = file.path.replace(/^\/+/, '');
    zip.file(cleanPath, file.content);
  });

  // 2. Inject cross-platform execution scripts
  const formattedRunScript = runScript || 'npm install && npm run dev';

  // Windows batch runner
  const runBat = `@echo off
echo Starting ${safeProjectName} via Synapse-OS...
${formattedRunScript}
pause
`;
  zip.file('run.bat', runBat);

  // Unix bash runner (with unix line-endings LF)
  const runSh = `#!/usr/bin/env bash
echo "Starting ${safeProjectName} via Synapse-OS..."
${formattedRunScript}
`;
  zip.file('run.sh', runSh.replace(/\r\n/g, '\n'));

  // 3. Ensure a fallback README.md is present with manual setup instructions
  const hasReadme = files.some(
    (f) => f.path.toLowerCase() === 'readme.md' || f.path.toLowerCase().endsWith('/readme.md')
  );

  if (!hasReadme) {
    const readmeContent = `# ${projectName}
Scaffolded via Synapse Forge.

## Quick Start
You can launch this project automatically using the included run scripts:

### Windows:
Double-click \`run.bat\` or run in terminal:
\`\`\`cmd
run.bat
\`\`\`

### macOS & Linux:
Make executable and run \`run.sh\`:
\`\`\`bash
chmod +x run.sh
./run.sh
\`\`\`

### Manual Setup:
\`\`\`bash
${formattedRunScript}
\`\`\`

## Included Files:
${files.map((f) => `- \`${f.path}\``).join('\n')}

---
*Generated by Synapse-OS Agentic Build Studio v2.0*
`;
    zip.file('README.md', readmeContent);
  }

  // 4. Generate the ZIP blob and trigger download using saveAs
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  saveAs(blob, `${safeProjectName}.zip`);
}
